enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
excluded-patches = "'Custom branding' 'Theme'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
excluded-patches = "'Custom branding' 'Change header' 'Theme'"

[photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
included-patches = "'Enable DCIM folders backup control'"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"